apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: forecast-system
data:
  custom.xml: |
    <yandex>
      <users>
        <forecast_user>
          <password>forecast_password</password>
          <networks>
            <ip>::/0</ip>
          </networks>
          <profile>default</profile>
          <quota>default</quota>
        </forecast_user>
      </users>
    </yandex>

